# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_threshold <- function(z, lambda) {
    .Call(`_LassoReg_soft_threshold`, z, lambda)
}

lasso_cda_cpp <- function(X, y, lambda, max_iter = 1000L, tol = 1e-6) {
    .Call(`_LassoReg_lasso_cda_cpp`, X, y, lambda, max_iter, tol)
}

